services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html
      - ./laravel.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: laravel_db
    environment:
      POSTGRES_USER: laravel-user
      POSTGRES_PASSWORD: vikki
      POSTGRES_DB: laravel
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    image: node:20
    container_name: react_app
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  pgdata: